services:
  web:
    build: ./app
    depends_on:
      - postgres
    ports:
      - 5002:5000
  
  postgres:
    image: postgres
    volumes:
      - data_base:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  data_base:
